apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-configserver
  template:
    metadata:
      labels:
        app: demo-configserver
    spec:
      containers:
      - image: ggnanasekaran77/configserver:dcc99427a45e8da727baa4cda770ac3c941772c3
        name: configserver
        ports:
        - containerPort: 8080