apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30090
  selector:
    app: demo-configserver
