apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-configserver