apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-configserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-configserver
    spec:
      containers:
      - image: ggnanasekaran77/configserver:b1428986203fc3f891488fc35062585844e55ddc
        name: configserver
        resources: {}
status: {}