apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-configserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-configserver
    spec:
      containers:
      - image: ggnanasekaran77/configserver:e2748f1bfe54154c617805b89eff73268b5ba0df
        name: configserver
        ports:
        - containerPort: 8080