apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-configserver
  name: demo-configserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-configserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-configserver
    spec:
      containers:
      - image: ggnanasekaran77/configserver:74d3f3f037a52ac54f9f564b96a36607195e2bba
        name: configserver
        resources: {}
status: {}